name: CI - HACS Validation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  hacs-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run HACS validation
        # The `hacs/action` composite action validates that the repository
        # meets all requirements for inclusion in the HACS default store.
        # A **category** input is mandatory (\"integration\" in our case).
        uses: hacs/action@main
        with:
          category: integration
